name: danplayer
description:
  A flutter danMaku player.
  It's based on video_player, make the ui and some danmaku functions.
  It has very much custom options for developer.
  The more infomation please read the document.
version: 0.0.2+hotfix1
author: gzlock88 <gzlock88@gmail.com>
homepage: https://github.com/gzlock/flutter_danplayer

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^0.10.2+5
  oktoast: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
